language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t josephreed/js-notebook

script:
  - docker run -e CI=true josephreed/js-notebook npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'js-notebook'
  env: 'Jsnotebook-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-576860479568'
  bucket_path: 'js-notebook'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
