version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes: 
      - .:/home/node/app
    command: ["npm", "run", "test"]
